### ISSUE TITLE
Wiki links to repository, not blog

### ISSUE THREAD

**Issue by mayaarguelles** [nyu-ossd-s19/tojimjiang-weekly#2]
on the class wiki page, the link you provided links to this repository, not the GitHub site

**Comment by tojimjiang** [comment]
Fixed #1 now links to [https://nyu-ossd-s19.github.io/tojimjiang-weekly/](https://nyu-ossd-s19.github.io/tojimjiang-weekly/)

**Comment by tojimjiang** [comment]
Fixed.
